# Generated by Django 4.1.7 on 2023-02-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_artist_works_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['artist']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='artist',
        ),
    ]
